name: Build with nexe (Windows)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js セットアップ + npm キャッシュ
      - name: Set up Node.js and cache npm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'  # devDependencies 内の nexe もここでキャッシュされる

      # 3. npm 依存関係インストール
      - name: Install npm dependencies
        run: npm ci

      # 4. nexe キャッシュ (Node ソースのダウンロード高速化)
      - name: Cache nexe node source
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.nexe
          key: ${{ runner.os }}-nexe-node-22
          restore-keys: |
            ${{ runner.os }}-nexe-node-

      # 5. exe ビルド (npx を使ってローカル nexe を実行)
      - name: Build executable with nexe
        run: npx nexe index.cjs -o app.exe --build -j 4-r ws -r node-fetch -r extract-zip

      # 6. ビルド成果物アップロード
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: app.exe
  run:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download built binary
        uses: actions/download-artifact@v4
        with:
          name: app-exe

      - name: Run exe with timeout
        shell: pwsh
        run: |
          $proc = Start-Process -FilePath "./app.exe" -PassThru
          $waitTime = 10000
          $proc.WaitForExit($waitTime)
          if (-not $proc.HasExited) {
            Write-Host "Timeout reached. Killing process..."
            $proc.Kill()
            exit 1
          }
