name: Build with nexe (Windows)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. リポジトリチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js セットアップ + npm キャッシュ
      - name: Set up Node.js and cache npm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 3. 依存関係を再インストール（adm-zip → unzipper に置き換え）
      - name: Install npm dependencies
        run: npm ci --force

      # 4. nexe キャッシュ
      - name: Cache nexe node source
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.nexe
          key: ${{ runner.os }}-nexe-node-22
          restore-keys: |
            ${{ runner.os }}-nexe-node-

      # 5. exe ビルド
      - name: Build executable with nexe
        run: npx nexe index.js -o app.exe --build -j 4 `
              -r ws `
              --resource "./node_modules/unzipper/**/*" `
              --resource "./node_modules/node-fetch/**/*"

      # 6. ビルド成果物アップロード
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: app.exe

  run:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download built binary
        uses: actions/download-artifact@v4
        with:
          name: app-exe

      - name: Use variables
        run: |
          echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}" >> $GITHUB_ENV
          echo "WS_URL=ws://127.0.0.1:24050/websocket/v2" >> $GITHUB_ENV

      - name: Run exe with timeout
        shell: pwsh
        run: |
          $proc = Start-Process -FilePath "./app.exe" -PassThru `
                                -RedirectStandardOutput "stdout.log" `
                                -RedirectStandardError "stderr.log"

          $waitTime = 60000
          $proc.WaitForExit($waitTime)

          if (-not $proc.HasExited) {
              Write-Host "Timeout reached, process still running. Killing..."
              $proc.Kill()
              Write-Host "Timeout finished — considered normal exit"
              exit 0
          }

          Write-Host "Process finished. Exit code: $($proc.ExitCode)"
          Get-Content stdout.log
          Get-Content stderr.log

          if ($proc.ExitCode -ne 0) {
              Write-Host "Process exited with error"
              exit 1
          }